// Generated by https://pagedraw.io/pages/8950
import React from 'react';
import './component_2.css';

function render() {
    return <div className="component_2-component_2">
        <div className="component_2-0">
            <div className="component_2-0-0" /> 
            <div className="component_2-text-7">
                {"Yao's Millionaire "}
            </div>
            <div className="component_2-0-2" /> 
        </div>
        <div className="component_2-1">
            <div className="component_2-1-0" /> 
            <div className="component_2-rectangle-8">
                <div className="component_2-1-1-0">
                    <div className="component_2-rectangle_2">
                        <div className="component_2-1-1-0-0-0">
                            <input type="text" placeholder="Room Code" className="component_2-text_input-6" /> 
                        </div>
                    </div>
                </div>
                <div className="component_2-1-1-1">
                    <div className="component_2-rectangle_3">
                        <div className="component_2-1-1-1-0-0">
                            <input type="text" placeholder="Score" className="component_2-text_input_2" /> 
                        </div>
                    </div>
                </div>
                <div className="component_2-1-1-2">
                    <div className="component_2-rectangle_4">
                        <div className="component_2-1-1-2-0-0">
                            <div className="component_2-text_4">Submit</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="component_2-1-2" /> 
        </div>
        <div className="component_2-2" /> 
    </div>;
};

export default function Yee2(props) {
    return render.apply({props: props});
}