// Generated by https://pagedraw.io/pages/8950
import React from 'react';
import './component_3.css';

function render() {
    return <div className="component_3-component_3">
        <div className="component_3-0">
            <div className="component_3-0-0" /> 
            <div className="component_3-text-3">
                {"Yao's Millionaire "}
            </div>
            <div className="component_3-0-2" /> 
        </div>
        <div className="component_3-1">
            <div className="component_3-1-0" /> 
            <div className="component_3-rectangle-4">
                <div className="component_3-1-1-0">
                    <img src="https://ucarecdn.com/a2e7063e-3661-4efc-a892-b64e70fb4920/" className="component_3-image-4" /> 
                </div>
                <div className="component_3-1-1-1">
                    <div className="component_3-text_2">{"BAMBOOZLED!!"}</div>
                </div>
            </div>
            <div className="component_3-1-2" /> 
        </div>
        <div className="component_3-2" /> 
    </div>;
};

export default function Yee3(props) {
    return render.apply({props: props});
}