// Generated by https://pagedraw.io/pages/8950
import React from 'react';
import './component_4.css';

function render() {
    return <div className="component_4-component_4">
        <div className="component_4-0">
            <div className="component_4-0-0" /> 
            <div className="component_4-text-8">
                {"Yao's Millionaire "}
            </div>
            <div className="component_4-0-2" /> 
        </div>
        <div className="component_4-1">
            <div className="component_4-1-0" /> 
            <div className="component_4-rectangle-2">
                <div className="component_4-1-1-0">
                    <img src="https://ucarecdn.com/beaa8606-135d-4b0a-9331-37379a31dcf1/" className="component_4-image-6" /> 
                </div>
                <div className="component_4-1-1-1">
                    <div className="component_4-text_2">
                        {"AYY LMAOOOOO!!"}
                    </div>
                </div>
            </div>
            <div className="component_4-1-2" /> 
        </div>
        <div className="component_4-2" /> 
    </div>;
};

export default function Yee4(props) {
    return render.apply({props: props});
}